algo: ppo
rl:
  lr: 0.001
  clip: 0.2
  entropy_coef: 0.05
  value_coef: 0.05
  gamma: 0.99
  ppo_epochs: 2
  gae_lambda: 0.95
  actor_model: "google/gemma-2-2b-it"
  judge_model: "Qwen/Qwen2.5-1.5B-Instruct"
